services:
  - type: web
    name: miniblog
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      PYTHONPATH=/opt/render/project/src \
      FLASK_APP=miniblog \
      FLASK_ENV=production \
      gunicorn --bind=0.0.0.0:$PORT --workers=4 --timeout=120 wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
