services:
  - type: web
    name: miniblog
    env: python
    buildCommand: |
      python -m pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: |
      export PYTHONPATH=/opt/render/project/src:$PYTHONPATH
      gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --chdir /opt/render/project/src 'wsgi:application'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: miniblog
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
