services:
  - type: web
    name: miniblog
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      mkdir -p instance
      FLASK_APP=miniblog FLASK_ENV=production python init_db.py
    startCommand: |
      FLASK_APP=miniblog \
      FLASK_ENV=production \
      gunicorn --bind 0.0.0.0:$PORT --workers 4 "miniblog:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
